function T = initializeStructure()
    T.x = [];
    T.y = [];
    T.z = [];
    T.radius = [];
    T.noCylinders = [];
    T.cLength = [];
    T.dx = [];
    T.dy = [];
    T.dz = [];
    T.theta = [];
    T.BO = [];
    T.maxBO = [];
    T.pSV = [];
    T.minZ = [];
    T.maxZ = [];
    T.ultimateUnion = [];
    T.shadowFraction = [];
    T.chunkUnion = [];
    T.chunkRawArea = [];
    T.chunkMinZ = [];
end